[package]
name = "toodoux"
version = "0.1.0"
license = "BSD-3-Clause"
authors = ["Dimitri Sabadie <dimitri.sabadie@gmail.com>"]
description = "A modern todo management tool"
keywords = ["todo"]
categories = ["development-tools"]
homepage = "https://github.com/phaazon/toodoux"
repository = "https://github.com/phaazon/toodoux"
readme = "README.md"
edition = "2018"

[dependencies]
chrono = { version = "0.4.11", features = ["serde"] }
colored = "1.9"
pulldown-cmark = { version = "0.7", optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
structopt = "0.3.13"
toml = "0.5.6"

[features]
default = ["markdown"]
markdown = ["pulldown-cmark"]
