[main]
tasks_file            = './intg-tests'
todo_alias            = 'TODO'
wip_alias             = 'WIP'
done_alias            = 'DONE'
cancelled_alias       = 'CANCELLED'
uid_col_name          = 'UID'
age_col_name          = 'Age'
spent_col_name        = 'Spent'
prio_col_name         = 'Prio'
project_col_name      = 'Project'
status_col_name       = 'Status'
description_col_name  = 'Description'
display_empty_cols    = false
max_description_lines = 2
